// automatically generated by the FlatBuffers compiler, do not modify

package serial;

@SuppressWarnings("unused")
public final class ItemType {
  private ItemType() { }
  public static final int Unknown = 0;
  public static final int TupleFormatAlpha = 1;

  public static final String[] names = { "Unknown", "TupleFormatAlpha", };

  public static String name(int e) { return names[e]; }
}

