// automatically generated by the FlatBuffers compiler, do not modify

package serial;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ProllyTreeNode extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ProllyTreeNode getRootAsProllyTreeNode(ByteBuffer _bb) { return getRootAsProllyTreeNode(_bb, new ProllyTreeNode()); }
  public static ProllyTreeNode getRootAsProllyTreeNode(ByteBuffer _bb, ProllyTreeNode obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public static boolean ProllyTreeNodeBufferHasIdentifier(ByteBuffer _bb) { return __has_identifier(_bb, "TUPM"); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ProllyTreeNode __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int keyItems(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int keyItemsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector keyItemsVector() { return keyItemsVector(new ByteVector()); }
  public ByteVector keyItemsVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer keyItemsAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer keyItemsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int keyOffsets(int j) { int o = __offset(6); return o != 0 ? bb.getShort(__vector(o) + j * 2) & 0xFFFF : 0; }
  public int keyOffsetsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ShortVector keyOffsetsVector() { return keyOffsetsVector(new ShortVector()); }
  public ShortVector keyOffsetsVector(ShortVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer keyOffsetsAsByteBuffer() { return __vector_as_bytebuffer(6, 2); }
  public ByteBuffer keyOffsetsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 2); }
  public int keyType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public int valueItems(int j) { int o = __offset(10); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int valueItemsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector valueItemsVector() { return valueItemsVector(new ByteVector()); }
  public ByteVector valueItemsVector(ByteVector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer valueItemsAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer valueItemsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public int valueOffsets(int j) { int o = __offset(12); return o != 0 ? bb.getShort(__vector(o) + j * 2) & 0xFFFF : 0; }
  public int valueOffsetsLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public ShortVector valueOffsetsVector() { return valueOffsetsVector(new ShortVector()); }
  public ShortVector valueOffsetsVector(ShortVector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer valueOffsetsAsByteBuffer() { return __vector_as_bytebuffer(12, 2); }
  public ByteBuffer valueOffsetsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 2); }
  public int valueType() { int o = __offset(14); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public int valueAddressOffsets(int j) { int o = __offset(16); return o != 0 ? bb.getShort(__vector(o) + j * 2) & 0xFFFF : 0; }
  public int valueAddressOffsetsLength() { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; }
  public ShortVector valueAddressOffsetsVector() { return valueAddressOffsetsVector(new ShortVector()); }
  public ShortVector valueAddressOffsetsVector(ShortVector obj) { int o = __offset(16); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer valueAddressOffsetsAsByteBuffer() { return __vector_as_bytebuffer(16, 2); }
  public ByteBuffer valueAddressOffsetsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 2); }
  public int addressArray(int j) { int o = __offset(18); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int addressArrayLength() { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector addressArrayVector() { return addressArrayVector(new ByteVector()); }
  public ByteVector addressArrayVector(ByteVector obj) { int o = __offset(18); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer addressArrayAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer addressArrayInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public int subtreeCounts(int j) { int o = __offset(20); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int subtreeCountsLength() { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector subtreeCountsVector() { return subtreeCountsVector(new ByteVector()); }
  public ByteVector subtreeCountsVector(ByteVector obj) { int o = __offset(20); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer subtreeCountsAsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public ByteBuffer subtreeCountsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 1); }
  public long treeCount() { int o = __offset(22); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int treeLevel() { int o = __offset(24); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createProllyTreeNode(FlatBufferBuilder builder,
      int keyItemsOffset,
      int keyOffsetsOffset,
      int keyType,
      int valueItemsOffset,
      int valueOffsetsOffset,
      int valueType,
      int valueAddressOffsetsOffset,
      int addressArrayOffset,
      int subtreeCountsOffset,
      long treeCount,
      int treeLevel) {
    builder.startTable(11);
    ProllyTreeNode.addTreeCount(builder, treeCount);
    ProllyTreeNode.addSubtreeCounts(builder, subtreeCountsOffset);
    ProllyTreeNode.addAddressArray(builder, addressArrayOffset);
    ProllyTreeNode.addValueAddressOffsets(builder, valueAddressOffsetsOffset);
    ProllyTreeNode.addValueOffsets(builder, valueOffsetsOffset);
    ProllyTreeNode.addValueItems(builder, valueItemsOffset);
    ProllyTreeNode.addKeyOffsets(builder, keyOffsetsOffset);
    ProllyTreeNode.addKeyItems(builder, keyItemsOffset);
    ProllyTreeNode.addTreeLevel(builder, treeLevel);
    ProllyTreeNode.addValueType(builder, valueType);
    ProllyTreeNode.addKeyType(builder, keyType);
    return ProllyTreeNode.endProllyTreeNode(builder);
  }

  public static void startProllyTreeNode(FlatBufferBuilder builder) { builder.startTable(11); }
  public static void addKeyItems(FlatBufferBuilder builder, int keyItemsOffset) { builder.addOffset(0, keyItemsOffset, 0); }
  public static int createKeyItemsVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createKeyItemsVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startKeyItemsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addKeyOffsets(FlatBufferBuilder builder, int keyOffsetsOffset) { builder.addOffset(1, keyOffsetsOffset, 0); }
  public static int createKeyOffsetsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(2, data.length, 2); for (int i = data.length - 1; i >= 0; i--) builder.addShort((short) data[i]); return builder.endVector(); }
  public static void startKeyOffsetsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(2, numElems, 2); }
  public static void addKeyType(FlatBufferBuilder builder, int keyType) { builder.addByte(2, (byte) keyType, (byte) 0); }
  public static void addValueItems(FlatBufferBuilder builder, int valueItemsOffset) { builder.addOffset(3, valueItemsOffset, 0); }
  public static int createValueItemsVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createValueItemsVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startValueItemsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addValueOffsets(FlatBufferBuilder builder, int valueOffsetsOffset) { builder.addOffset(4, valueOffsetsOffset, 0); }
  public static int createValueOffsetsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(2, data.length, 2); for (int i = data.length - 1; i >= 0; i--) builder.addShort((short) data[i]); return builder.endVector(); }
  public static void startValueOffsetsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(2, numElems, 2); }
  public static void addValueType(FlatBufferBuilder builder, int valueType) { builder.addByte(5, (byte) valueType, (byte) 0); }
  public static void addValueAddressOffsets(FlatBufferBuilder builder, int valueAddressOffsetsOffset) { builder.addOffset(6, valueAddressOffsetsOffset, 0); }
  public static int createValueAddressOffsetsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(2, data.length, 2); for (int i = data.length - 1; i >= 0; i--) builder.addShort((short) data[i]); return builder.endVector(); }
  public static void startValueAddressOffsetsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(2, numElems, 2); }
  public static void addAddressArray(FlatBufferBuilder builder, int addressArrayOffset) { builder.addOffset(7, addressArrayOffset, 0); }
  public static int createAddressArrayVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createAddressArrayVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startAddressArrayVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addSubtreeCounts(FlatBufferBuilder builder, int subtreeCountsOffset) { builder.addOffset(8, subtreeCountsOffset, 0); }
  public static int createSubtreeCountsVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createSubtreeCountsVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startSubtreeCountsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addTreeCount(FlatBufferBuilder builder, long treeCount) { builder.addLong(9, treeCount, 0L); }
  public static void addTreeLevel(FlatBufferBuilder builder, int treeLevel) { builder.addByte(10, (byte) treeLevel, (byte) 0); }
  public static int endProllyTreeNode(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // key_items
    builder.required(o, 6);  // key_offsets
    return o;
  }
  public static void finishProllyTreeNodeBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset, "TUPM"); }
  public static void finishSizePrefixedProllyTreeNodeBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset, "TUPM"); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ProllyTreeNode get(int j) { return get(new ProllyTreeNode(), j); }
    public ProllyTreeNode get(ProllyTreeNode obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

